spring:
  redis:
    host: 39.101.219.28
    password: redis
    port: 6379
    # 连接池超时时间
    timeout: 3000
    jedis:
      pool:
        # 连接池最大阻塞等待时间（负值表示没有限制）
        max-wait: 30000
        # 连接池最大连接数（负值无限制）
        max-active: 100
        # 连接池最大空闲连接数
        max-idle: 20
        # 连接池最小空闲连接数
        min-idle: 8

